//! Signed requests used by external topology reconcilers.

use anyhow::{Context, Result};
use iroh_base::{EndpointId, SecretKey, Signature};
use serde::{Deserialize, Serialize};
use sha2::{Digest, Sha256};

use crate::{CONTROL_PROTOCOL_VERSION, InviteInfo, InviteResult, ensure_protocol_version};

/// HTTP authorization scheme used by Provisioner requests.
pub const PROVISIONER_AUTH_SCHEME: &str = "AgentScale-Ed25519";
const REQUEST_DOMAIN: &[u8] = b"agent-scale-control-provisioner-http-v1\0POST\0/v1/provisioner\0";

/// A topology operation authorized by a registered Provisioner identity.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "action", rename_all = "snake_case")]
pub enum ProvisionerAction {
    GetTopology,
    InviteCenter {
        name: String,
        ttl_secs: u64,
        /// URL-safe, cryptographically random secret generated by the caller.
        secret: String,
    },
    InviteEdge {
        owner: String,
        name: String,
        ttl_secs: u64,
        /// URL-safe, cryptographically random secret generated by the caller.
        secret: String,
    },
    RevokeInvite {
        invite_id: String,
    },
    RemoveCenter {
        name: String,
    },
    RemoveEdge {
        owner: String,
        name: String,
    },
    TransferEdge {
        owner: String,
        name: String,
        endpoint_id: String,
        new_owner: String,
    },
}

/// JSON request body. `request_id` is an idempotency key for mutations.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProvisionerRequest {
    pub protocol_version: u32,
    pub audience: String,
    pub request_id: String,
    pub issued_at: i64,
    pub expected_revision: Option<u64>,
    pub action: ProvisionerAction,
}

impl ProvisionerRequest {
    /// Serialize this request and sign the exact HTTP body bytes.
    pub fn sign(
        key: &SecretKey,
        audience: String,
        request_id: String,
        issued_at: i64,
        expected_revision: Option<u64>,
        action: ProvisionerAction,
    ) -> Result<ProvisionerHttpRequest> {
        let request = Self {
            protocol_version: CONTROL_PROTOCOL_VERSION,
            audience,
            request_id,
            issued_at,
            expected_revision,
            action,
        };
        ProvisionerHttpRequest::new(request, key)
    }

    pub fn verify_protocol(&self) -> Result<()> {
        ensure_protocol_version(self.protocol_version)
    }
}

/// Ready-to-send HTTP request material for Rust clients.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct ProvisionerHttpRequest {
    pub body: Vec<u8>,
    pub authorization: String,
}

impl ProvisionerHttpRequest {
    pub fn new(request: ProvisionerRequest, key: &SecretKey) -> Result<Self> {
        let body = serde_json::to_vec(&request).context("serialize provisioner request")?;
        let authorization = provisioner_authorization(key, &body);
        Ok(Self { body, authorization })
    }

    pub fn verify(&self) -> Result<EndpointId> {
        verify_provisioner_authorization(&self.authorization, &self.body)
    }
}

/// Build the HTTP `Authorization` value for the exact bytes sent as the body.
pub fn provisioner_authorization(key: &SecretKey, body: &[u8]) -> String {
    let signature = key.sign(&provisioner_signing_bytes(body));
    format!(
        "{PROVISIONER_AUTH_SCHEME} {}:{}",
        key.public(),
        hex::encode(signature.to_bytes())
    )
}

/// Verify an HTTP `Authorization` value against the exact received body bytes.
pub fn verify_provisioner_authorization(value: &str, body: &[u8]) -> Result<EndpointId> {
    let credentials = value
        .strip_prefix(PROVISIONER_AUTH_SCHEME)
        .and_then(|value| value.strip_prefix(' '))
        .context("unsupported provisioner authorization scheme")?;
    let (endpoint_id, encoded_signature) = credentials
        .split_once(':')
        .context("malformed provisioner authorization credentials")?;
    anyhow::ensure!(!endpoint_id.is_empty(), "missing provisioner endpoint id");
    anyhow::ensure!(
        !encoded_signature.is_empty() && !encoded_signature.contains(':'),
        "malformed provisioner signature"
    );
    let endpoint_id: EndpointId = endpoint_id.parse().context("invalid provisioner endpoint id")?;
    let signature_bytes = hex::decode(encoded_signature).context("invalid provisioner signature encoding")?;
    let signature_bytes: [u8; Signature::LENGTH] = signature_bytes
        .try_into()
        .map_err(|_| anyhow::anyhow!("invalid provisioner signature length"))?;
    endpoint_id
        .verify(
            &provisioner_signing_bytes(body),
            &Signature::from_bytes(&signature_bytes),
        )
        .context("invalid provisioner request signature")?;
    Ok(endpoint_id)
}

/// Language-neutral signature preimage: a fixed method/path domain followed by
/// the SHA-256 digest of the exact HTTP request body bytes.
pub fn provisioner_signing_bytes(body: &[u8]) -> Vec<u8> {
    let digest = Sha256::digest(body);
    let mut bytes = Vec::with_capacity(REQUEST_DOMAIN.len() + digest.len());
    bytes.extend_from_slice(REQUEST_DOMAIN);
    bytes.extend_from_slice(&digest);
    bytes
}

/// Stable digest used to reject reuse of an idempotency key for another action.
pub fn action_hash(action: &ProvisionerAction) -> Result<String> {
    let mut hasher = Sha256::new();
    hasher.update(b"agent-scale-control-provisioner-action-v1\0");
    hasher.update(serde_json::to_vec(action).context("serialize provisioner action")?);
    Ok(hex::encode(hasher.finalize()))
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ManagedEdgeInfo {
    pub name: String,
    pub endpoint_id: String,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ManagedCenterInfo {
    pub name: String,
    pub endpoint_id: String,
    pub edges: Vec<ManagedEdgeInfo>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
pub struct ProvisionerTopology {
    pub revision: u64,
    pub centers: Vec<ManagedCenterInfo>,
    pub invites: Vec<InviteInfo>,
}

#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[serde(tag = "result", content = "data", rename_all = "snake_case")]
pub enum ProvisionerResponse {
    Topology(ProvisionerTopology),
    Invite(InviteResult),
    Ok { revision: u64 },
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn signature_covers_action_and_revision() {
        let key = SecretKey::generate();
        let signed = ProvisionerRequest::sign(
            &key,
            "prod".into(),
            "request-1".into(),
            123,
            Some(7),
            ProvisionerAction::RemoveCenter { name: "job".into() },
        )
        .unwrap();
        assert_eq!(signed.verify().unwrap(), key.public());

        let mut tampered = signed;
        tampered.body.push(b' ');
        assert!(tampered.verify().is_err());
    }

    #[test]
    fn language_neutral_test_vector_is_stable() {
        let key = SecretKey::try_from(&[7u8; 32][..]).unwrap();
        let signed = ProvisionerRequest::sign(
            &key,
            "prod".into(),
            "request-1".into(),
            1_700_000_000,
            Some(7),
            ProvisionerAction::RemoveCenter { name: "job-1".into() },
        )
        .unwrap();
        assert_eq!(
            key.public().to_string(),
            "ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c"
        );
        assert_eq!(
            String::from_utf8(signed.body).unwrap(),
            r#"{"protocol_version":3,"audience":"prod","request_id":"request-1","issued_at":1700000000,"expected_revision":7,"action":{"action":"remove_center","name":"job-1"}}"#
        );
        assert_eq!(
            signed.authorization,
            "AgentScale-Ed25519 ea4a6c63e29c520abef5507b132ec5f9954776aebebe7b92421eea691446d22c:f76ea19f84a5b1bc5c0ef632222fefe08aff7813d07e09b0e88a15f7359667a6665ce8f1424da19256a195b0a1d7d350224266d6378c3c5b7ea0ccd28b1dd506"
        );
    }
}
