x-local-control-image: &local-control-image
  image: agent-scale-control:local

x-local-relay-image: &local-relay-image
  image: agent-scale-relay:local

services:
  bootstrap:
    <<: *local-control-image
    build:
      context: .
      target: control
  control: *local-control-image
  relay:
    <<: *local-relay-image
    build:
      context: .
      target: relay
