# Copyright 2026 agent-scale contributors
# SPDX-License-Identifier: Apache-2.0

[default.extend-words]
iroh = "iroh"

[default.extend-identifiers]
MPORT = "MPORT"

[files]
extend-exclude = [
  ".upstreams/**",
  "licenses/dependencies/**",
  "submodules/**",
  "target/**",
  "vendor/iroh-blobs/**",
]
