[package]
edition.workspace = true
license.workspace = true
name = "scale-transport"
publish = false
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = { workspace = true }
bao-tree = "0.16"
futures-util = { workspace = true }
iroh = "1.0.3"
iroh-blobs = { version = "0.103", features = ["fs-store"] }
protocol = { package = "scale-protocol", path = "../protocol" }
rustls = { version = "0.23", default-features = false, features = ["ring"] }
tempfile = "3"
tokio = { workspace = true }

[lints]
workspace = true
