#!/usr/bin/env -S uv run --script
# /// script
# requires-python = ">=3.14"
# dependencies = []
# ///
"""Regenerate fd-lib/rg-lib Cargo.toml from pinned upstream manifests.

The wrapper crates (fd-lib, rg-lib) compile upstream fd/ripgrep source as a
library. Their dependency lists must match upstream's, minus:

  - path dependencies (rg's grep/ignore point at workspace crates) -> use the
    crates.io version instead.
  - optional dependencies tied to features we don't enable (fd's clap_complete
    for `completions`, jemalloc for `use-jemalloc`).

Run after updating `scripts/upstreams.lock` and running `cargo x init`. Runs via
uv (`./scripts/sync-deps.py`),
which picks an interpreter satisfying requires-python (>=3.14).
"""

import sys
import tomllib
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent

# These optional dependencies would add unused code because the wrappers do not
# enable their owning features.
# rg KEEPS tikv-jemallocator: its `#[global_allocator]` is active on musl
# (cfg matches the dependency's cfg), so the crate must be linked there.
# fd drops it: fd's allocator block is gated on the `use-jemalloc` feature,
# which we don't enable, so the reference is cfg'd out.
DROP = {
    "fd": {"clap_complete", "tikv-jemallocator"},
    "rg": set(),
}

TARGETS = {
    "fd": {
        "manifest": ROOT / ".upstreams/fd/Cargo.toml",
        "out": ROOT / "crates/fd-lib/Cargo.toml",
        "name": "fd-lib",
        "license": "Apache-2.0 AND MIT",
    },
    "rg": {
        "manifest": ROOT / ".upstreams/ripgrep/Cargo.toml",
        "out": ROOT / "crates/rg-lib/Cargo.toml",
        "name": "rg-lib",
        "license": "Apache-2.0 AND MIT AND BSD-3-Clause",
    },
}


def fmt_features(features):
    return "[" + ", ".join(f'"{f}"' for f in features) + "]"


def render_dep(name, spec):
    """Render a single dependency line, stripping `path` and `optional`."""
    if isinstance(spec, str):
        return f'{name} = "{spec}"'
    parts = []
    if "version" in spec:
        parts.append(f'version = "{spec["version"]}"')
    if spec.get("default-features") is False:
        parts.append("default-features = false")
    if "features" in spec:
        parts.append(f"features = {fmt_features(spec['features'])}")
    # Wrapper manifests must resolve independently of the upstream workspace;
    # optional dependencies were already filtered by the owning feature.
    return f'{name} = {{ {", ".join(parts)} }}'


def render_deps(deps, drop):
    lines = []
    # Match Taplo's deterministic key ordering so generation and formatting are
    # idempotent gates rather than competing rewrites.
    for name, spec in sorted(deps.items()):
        if name in drop:
            continue
        if isinstance(spec, dict) and spec.get("optional"):
            continue
        lines.append(render_dep(name, spec))
    return lines


def generate(key, check):
    cfg = TARGETS[key]
    manifest = tomllib.load(open(cfg["manifest"], "rb"))
    drop = DROP.get(key, set())

    # Pin the wrapper to upstream's version so the compiled CLI reports the real
    # fd/rg version: clap's `version` attr expands to this crate's
    # CARGO_PKG_VERSION. Falls back to the workspace version if upstream inherits
    # its own version from a workspace (a dict, not a literal string).
    upstream_version = manifest.get("package", {}).get("version")
    version_line = (
        f'version = "{upstream_version}"'
        if isinstance(upstream_version, str)
        else "version.workspace = true"
    )

    out = [
        "# AUTO-GENERATED by sync-deps.py from upstream Cargo.toml. Do not edit by hand.",
        "[package]",
        "edition.workspace = true",
        f'license = "{cfg["license"]}"',
        f'name = "{cfg["name"]}"',
        "publish = false",
        version_line,
        "",
        "[dependencies]",
    ]
    out += render_deps(manifest.get("dependencies", {}), drop)

    for tname, tbody in manifest.get("target", {}).items():
        tdeps = tbody.get("dependencies", {})
        if not tdeps:
            continue
        lines = render_deps(tdeps, drop)
        if lines:
            out.append("")
            # Keep single quotes around the cfg() expr — it may contain
            # double-quoted strings like target_os = "redox".
            out.append(f"[target.'{tname}'.dependencies]")
            out += lines

    out.append("")
    text = "\n".join(out)
    path = cfg["out"]
    if check:
        if path.read_text() != text:
            print(f"out of date: {path.relative_to(ROOT)}", file=sys.stderr)
            return False
        print(f"checked {path.relative_to(ROOT)}")
    else:
        path.write_text(text)
        print(f"wrote {path.relative_to(ROOT)} ({len(render_deps(manifest.get('dependencies', {}), drop))} deps)")
    return True


def main():
    args = sys.argv[1:]
    check = "--check" in args
    keys = [arg for arg in args if arg != "--check"] or list(TARGETS)
    valid = True
    for key in keys:
        if key not in TARGETS:
            print(f"unknown target: {key} (choose from {list(TARGETS)})", file=sys.stderr)
            sys.exit(1)
        valid = generate(key, check) and valid
    if not valid:
        sys.exit(1)


if __name__ == "__main__":
    main()
